 const CART_TYPES = {
   TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
   ADD_ITEM: 'ADD_ITEM',
   REMOVE_ITEM: 'REMOVE_ITEM',
   DECREASE_ITEM_QUANTITY:'DECREASE_ITEM_QUANTITY'
 }

export default CART_TYPES